name:                Projeto
version:             0.1.0.0
github:              "github.com/ufabc-bcc/paradigmas-2021-q2-projeto-final-WesleyAxel"
license:             BSD3
author:              "Wesley Axel de Barros"
maintainer:          "w.barros@aluno.ufabc.edu.br"
copyright:           "2021 Wesley Axel"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/ufabc-bcc/paradigmas-2021-q2-projeto-final-WesleyAxel>

dependencies:
- base >= 4.7 && < 5
- threepenny-gui >= 0.9
- containers >= 0.6.2.1
- binary >= 0.8.8.0
- utf8-string >= 0.10.12.0
- lzo >= 0.1.0.0
- bytestring >= 0.10.12.0
- timeit >= 2.0

library:
  source-dirs: src

executables:
  Projeto-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Projeto
    - threepenny-gui
    - containers
    - binary
    - utf8-string
    - lzo
    - bytestring
    - timeit

